name: Linux

on:
  workflow_call:

jobs:
  docs_link_spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/ci/docs_check.sh

  test_on_alpine:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: apk add -U git
      # https://github.com/actions/checkout/issues/1169
      - run: git config --system --add safe.directory '*'
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build test

  test_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build test

  aof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: ./.github/ci/test_aof.sh

  c_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build c_sample -Drelease

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build fuzz -- smoke

  # Check some build steps that would otherwise not get checked.
  # Things like "go_client", "java_client", "dotnet_client" are excluded here
  # because they get run in their own CI
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./scripts/install_zig.sh
      - run: zig/zig build build_benchmark_ewah
      - run: zig/zig build build_benchmark_binary_search
      - run: zig/zig build build_benchmark_segmented_array
      - run: zig/zig build -Dtracer-backend=tracy

  # Run simulator once for each state machine, using commit hash as a random, but also deterministic
  # seed.
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build simulator_run -Dsimulator-state-machine=accounting -Drelease -- ${{ github.sha }}
      - run: zig/zig build simulator_run -Dsimulator-state-machine=testing    -Drelease -- ${{ github.sha }}
